### ISSUE TITLE
[Missing Image]: Test new issue form

### ISSUE THREAD

**Issue by nexensys** [ErrorGamer2000/github-readme-blog-post-action#2]
### What is the title of the post that the image was supposed to be for?

Post Title Here

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Workflow configuration yml file

```yml
on:
  push:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    name: Update the example on the README
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate
        uses: ./
        with:
          feed_urls: "https://dev.to/feed,https://cprss.s3.amazonaws.com/javascriptweekly.com.xml,https://www.echojs.com/rss"
          max_posts_per_url: 5
          position_indicator: "post-list"
          locale: "en-US"
          time_zone: "America/Denver"
          output_dir: "generated_files"
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save generated content
          skip_checkout: true
```

### Action errors and warnings

```Shell
None
```
